- name: Install Nginx on Ubuntu
  apt:
    name: nginx
    state: present
    notify:
      - Restart Nginx
  when: ansible_distribution == "Ubuntu"

- name: Install Nginx on CentOS
  yum:
    name: nginx
    state: present
    notify:
      - Restart Nginx
  when: ansible_distribution == "CentOS"

- name: Install Jenkins keyring on Ubuntu
  shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins repository on Ubuntu
  shell: echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: Install openjdk-11-jdk on Ubuntu
  apt:
    name: openjdk-11-jdk
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Update apt package cache
  apt:
    update_cache: yes

- name: Install Jenkins on Ubuntu
  apt:
    name: jenkins
    state: present
    notify:
      - Enable Nginx and Jenkins services
  when: ansible_distribution == "Ubuntu"

- name: Install Jenkins on CentOS
  yum:
    name: jenkins
    state: present
    notify:
      - Enable Nginx and Jenkins services
  when: ansible_distribution == "CentOS"

- name: Create Nginx configuration file for Jenkins
  become: true
  file:
    path: /etc/nginx/conf.d/jenkins.conf
    state: touch

- name: Configure Nginx as reverse proxy for Jenkins
  blockinfile:
    path: /etc/nginx/conf.d/jenkins.conf
    block: |
      server {
          listen 80;
          server_name {{ jenkins_server_name }};
          access_log /var/log/nginx/jenkins.access.log;

          location / {
              proxy_pass http://{{ jenkins_server_name }}:{{ jenkins_http_port }};
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Reboot the system
  become: true
  reboot:
    reboot_timeout: 3600
    msg: "Reboot initiated by Ansible"
